# Generated by Django 3.2.9 on 2022-02-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty_list', '0002_recept_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='recepty/'),
        ),
    ]
