# Generated by Django 3.2.9 on 2022-02-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty_list', '0006_alter_recept_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recept',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recept',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='Ingredients', to='recepty_list.Ingredients'),
        ),
    ]
