# Generated by Django 3.2.9 on 2022-02-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepty_list', '0007_auto_20220224_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
