# Generated by Django 4.0.2 on 2022-02-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty_list', '0008_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'Hard')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='recept',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='Ingredient', to='recepty_list.Ingredient'),
        ),
    ]
