# Generated by Django 4.0.2 on 2022-03-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty_list', '0009_alter_recept_difficulty_alter_recept_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='thumbnail',
            field=models.ImageField(upload_to='recepty/'),
        ),
    ]
